[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'cocopon/iceberg.vim'
if = "!has('mac')"
hook_add = '''
  augroup MyColor
    autocmd!
    autocmd VimEnter * nested colorscheme iceberg
  augroup END
'''

[[plugins]]
repo = 'vim-airline/vim-airline'
depends = ['vim-airline/vim-airline-themes']

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

# [[plugins]]
# repo = 'neoclide/coc.nvim'
# rev = 'release'
# on_i = 1
# merged = '0'

[[plugins]]
repo = 'w0rp/ale'
hook_add = '''
  let g:ale_fixers = {
  \   'go': ['goimports', 'go mod', 'go vet', 'gotype', 'gosimple', 'golangserver', 'golangci-lint'],
  \   'ruby': ['rufo'],
  \ }
  let g:ale_fix_on_save = 1
  let g:ale_echo_msg_error_str = 'E'
  let g:ale_echo_msg_warning_str = 'W'
  let g:ale_echo_msg_format = '[%linter%] %s [%severity%]'
  let g:ale_open_list = 1
  let g:ale_lint_on_save = 1
  let g:ale_lint_on_text_changed = 0
  let g:ale_set_loclist = 0
  let g:ale_set_quickfix = 0
'''

[[plugins]]
repo = 'guns/xterm-color-table.vim'

[[plugins]]
repo = 'Yggdroot/indentLine'
hook_add = '''
  let g:indentLine_char = '¦'
  let g:indentLine_color_term = 236
'''

[[plugins]]
repo = 'Shougo/vinarise'

[[plugins]]
repo = 'Shougo/denite.nvim'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = '''
  let g:deoplete#enable_at_startup = 1
'''

[[plugins]]
repo = 'prabirshrestha/vim-lsp'

[[plugins]]
repo = 'mattn/vim-lsp-settings'

[[plugins]]
repo = 'lighttiger2505/deoplete-vim-lsp'

[[plugins]]
repo = 'mattn/vim-sonictemplate'
hook_add = '''
  let g:sonictemplate_vim_template_dir = expand('~/.config/nvim/sonictemplate')
'''
